name: Snapshot

on:
  push:
    branches: [main]
  pull_request:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v2.9.0
          args: release --snapshot --clean